theme: jekyll-theme-cayman
title: Quality-Diversity optimisation algorithms
description: This webpage intend to list papers related to QD, links to tutorials and workshops, and pointers to existing implementations of QD algorithms.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md